{
 "title": "HomeWorkGrafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU (в процентах, 100 – idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Свободное место на файловой системе",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/(dev|proc|sys|run).*\"}",
     "legendFormat": "Свободное место"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/(dev|proc|sys|run).*\"}",
     "legendFormat": "Общий размер диска"
    }
   ]
  },
  {
   "title": "CPU Load Average (1 минута)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "CPU Load Average (5  минут)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "CPU Load Average (15 минут)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Свободное место на файловой системе %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/(dev|proc|sys|run).*\"} \n/ \nnode_filesystem_size_bytes{fstype=~\"ext4|xfs\", mountpoint!~\"/(dev|proc|sys|run).*\"}) * 100"
    }
   ]
  }
 ]
}