---
# Основной playbook: установка ClickHouse, Vector и Lighthouse
# с использованием Ansible roles

- name: Install ClickHouse
  hosts: clickhouse
  become: true
  roles:
    - role: clickhouse
      vars:
        clickhouse_clean_db: false
        clickhouse_user: ubuntu

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - role: vector-role

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - role: lighthouse-role