---
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.186.110
  children:
    nexus_group:  # ← другое имя
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ubuntu