[tox]
minversion = 3.0
envlist = py39-molecule
skipsdist = true

[testenv]
setenv =
    DOCKER_HOST = unix:///var/run/docker.sock
passenv =
    HOME
    TERM
    DOCKER_*
    MOLECULE_*
deps =
    ansible>=7.0.0
    molecule==6.0.3
    molecule-docker==1.1.0
    docker
commands =
    molecule test -s compatibility --destroy always